// ERP Mock Data — Pharmacy Distribution ERP

// ===================== DASHBOARD KPIs =====================
export const dashboardKPIs = {
  totalSalesToday: 128450.0,
  totalInvoices: 342,
  totalOutstanding: 47200.0,
  totalProducts: 1248,
  nearExpiryProducts: 23,
  lowStockProducts: 18,
  pendingGRNs: 7,
  pendingApprovals: 12,
};

export const recentActivities = [
  {
    id: 1,
    user: "Amal Perera",
    action: "Posted Invoice",
    document: "INV-2024-0342",
    module: "Invoice Center",
    time: "2 min ago",
    status: "Posted",
  },
  {
    id: 2,
    user: "Nimal Silva",
    action: "Created GRN",
    document: "GRN-2024-0128",
    module: "Inventory",
    time: "15 min ago",
    status: "Draft",
  },
  {
    id: 3,
    user: "Saman Kumara",
    action: "Approved Journal",
    document: "JNL-2024-0089",
    module: "Finance",
    time: "32 min ago",
    status: "Approved",
  },
  {
    id: 4,
    user: "Kamali Fernando",
    action: "Added User",
    document: "USR-0056",
    module: "Control Center",
    time: "1 hr ago",
    status: "Active",
  },
  {
    id: 5,
    user: "Priya Ratne",
    action: "Batch Hold",
    document: "BATCH-PARACE-0023",
    module: "Compliance",
    time: "2 hr ago",
    status: "On Hold",
  },
  {
    id: 6,
    user: "Amal Perera",
    action: "Credit Note",
    document: "CN-2024-0045",
    module: "Invoice Center",
    time: "3 hr ago",
    status: "Pending",
  },
];

// ===================== CONTROL CENTER =====================
export const companies = [
  {
    id: 1,
    name: "PharmaDist Lanka Pvt Ltd",
    legalName: "PharmaDist Lanka Private Limited",
    regNo: "PV00123456",
    tin: "TIN-987654321",
    vat: "VAT-123456789",
    address: "45 Galle Road, Colombo 03",
    phone: "+94 11 234 5678",
    email: "info@pharmadist.lk",
    status: "Active",
  },
];

export const branches = [
  {
    id: 1,
    branchName: "Head Office",
    branchCode: "HO",
    address: "45 Galle Road, Colombo 03",
    contactNo: "+94 11 234 5678",
    email: "ho@pharmadist.lk",
    manager: "Suresh Jayawardena",
    status: "Active",
  },
  {
    id: 2,
    branchName: "Kandy Branch",
    branchCode: "KDY",
    address: "12 Peradeniya Rd, Kandy",
    contactNo: "+94 81 222 3344",
    email: "kandy@pharmadist.lk",
    manager: "Chaminda Bandara",
    status: "Active",
  },
  {
    id: 3,
    branchName: "Galle Branch",
    branchCode: "GLL",
    address: "7 Wakwella Rd, Galle",
    contactNo: "+94 91 222 5566",
    email: "galle@pharmadist.lk",
    manager: "Nalini Perera",
    status: "Inactive",
  },
];

export const users = [
  {
    id: 1,
    name: "Amal Perera",
    email: "amal@pharmadist.lk",
    mobile: "+94 71 123 4567",
    employeeId: "EMP-001",
    department: "Sales",
    designation: "Sales Manager",
    branch: "Head Office",
    role: "Sales Manager",
    status: "Active",
  },
  {
    id: 2,
    name: "Nimal Silva",
    email: "nimal@pharmadist.lk",
    mobile: "+94 77 234 5678",
    employeeId: "EMP-002",
    department: "Warehouse",
    designation: "Warehouse Manager",
    branch: "Head Office",
    role: "Warehouse Manager",
    status: "Active",
  },
  {
    id: 3,
    name: "Saman Kumara",
    email: "saman@pharmadist.lk",
    mobile: "+94 76 345 6789",
    employeeId: "EMP-003",
    department: "Finance",
    designation: "Finance Manager",
    branch: "Head Office",
    role: "Finance Manager",
    status: "Active",
  },
  {
    id: 4,
    name: "Kamali Fernando",
    email: "kamali@pharmadist.lk",
    mobile: "+94 72 456 7890",
    employeeId: "EMP-004",
    department: "Administration",
    designation: "System Admin",
    branch: "Head Office",
    role: "System Admin",
    status: "Active",
  },
  {
    id: 5,
    name: "Priya Ratne",
    email: "priya@pharmadist.lk",
    mobile: "+94 75 567 8901",
    employeeId: "EMP-005",
    department: "Compliance",
    designation: "Compliance Officer",
    branch: "Kandy Branch",
    role: "Compliance Officer",
    status: "Active",
  },
];

export const roles = [
  {
    id: 1,
    name: "System Admin",
    description: "Full system access",
    userCount: 1,
    status: "Active",
  },
  {
    id: 2,
    name: "Finance Manager",
    description: "Finance module full access",
    userCount: 2,
    status: "Active",
  },
  {
    id: 3,
    name: "Sales Manager",
    description: "Invoice and sales access",
    userCount: 4,
    status: "Active",
  },
  {
    id: 4,
    name: "Warehouse Manager",
    description: "Inventory module access",
    userCount: 3,
    status: "Active",
  },
  {
    id: 5,
    name: "Compliance Officer",
    description: "Compliance center access",
    userCount: 2,
    status: "Active",
  },
  {
    id: 6,
    name: "Sales Representative",
    description: "Invoice view and create",
    userCount: 8,
    status: "Active",
  },
];

export const designations = [
  {
    id: 1,
    title: "Managing Director",
    department: "Management",
    status: "Active",
  },
  { id: 2, title: "Finance Manager", department: "Finance", status: "Active" },
  { id: 3, title: "Accountant", department: "Finance", status: "Active" },
  {
    id: 4,
    title: "Warehouse Manager",
    department: "Warehouse",
    status: "Active",
  },
  { id: 5, title: "Sales Manager", department: "Sales", status: "Active" },
  {
    id: 6,
    title: "Sales Representative",
    department: "Sales",
    status: "Active",
  },
  {
    id: 7,
    title: "Compliance Officer",
    department: "Compliance",
    status: "Active",
  },
  { id: 8, title: "System Admin", department: "IT", status: "Active" },
];

export const auditLogs = [
  {
    id: 1,
    dateTime: "2024-01-15 09:23:11",
    user: "Amal Perera",
    module: "Invoice Center",
    action: "POST",
    table: "invoices",
    recordId: "INV-2024-0342",
    ip: "192.168.1.10",
    status: "Success",
  },
  {
    id: 2,
    dateTime: "2024-01-15 09:10:45",
    user: "Nimal Silva",
    module: "Inventory",
    action: "CREATE",
    table: "grns",
    recordId: "GRN-2024-0128",
    ip: "192.168.1.15",
    status: "Success",
  },
  {
    id: 3,
    dateTime: "2024-01-15 08:55:30",
    user: "Kamali Fernando",
    module: "Control Center",
    action: "CREATE",
    table: "users",
    recordId: "EMP-056",
    ip: "192.168.1.5",
    status: "Success",
  },
  {
    id: 4,
    dateTime: "2024-01-15 08:30:00",
    user: "Priya Ratne",
    module: "Compliance",
    action: "UPDATE",
    table: "batch_holds",
    recordId: "BATCH-0023",
    ip: "192.168.2.20",
    status: "Success",
  },
];

// ===================== FINANCE =====================
export const chartOfAccounts = [
  {
    id: 1,
    code: "1000",
    name: "Cash and Cash Equivalents",
    type: "Assets",
    parentAccount: null,
    isCashBank: true,
    status: "Active",
  },
  {
    id: 2,
    code: "1100",
    name: "Accounts Receivable",
    type: "Assets",
    parentAccount: null,
    isCashBank: false,
    status: "Active",
  },
  {
    id: 3,
    code: "1200",
    name: "Inventory",
    type: "Assets",
    parentAccount: null,
    isCashBank: false,
    status: "Active",
  },
  {
    id: 4,
    code: "2000",
    name: "Accounts Payable",
    type: "Liabilities",
    parentAccount: null,
    isCashBank: false,
    status: "Active",
  },
  {
    id: 5,
    code: "3000",
    name: "Share Capital",
    type: "Equity",
    parentAccount: null,
    isCashBank: false,
    status: "Active",
  },
  {
    id: 6,
    code: "4000",
    name: "Sales Revenue",
    type: "Income",
    parentAccount: null,
    isCashBank: false,
    status: "Active",
  },
  {
    id: 7,
    code: "5000",
    name: "Cost of Goods Sold",
    type: "Cost of Sales",
    parentAccount: null,
    isCashBank: false,
    status: "Active",
  },
  {
    id: 8,
    code: "6000",
    name: "Operating Expenses",
    type: "Expenses",
    parentAccount: null,
    isCashBank: false,
    status: "Active",
  },
];

export const journalEntries = [
  {
    id: 1,
    refNo: "JNL-2024-0089",
    date: "2024-01-15",
    description: "Sales revenue posting for Jan batch",
    createdBy: "Saman Kumara",
    totalDebit: 128450.0,
    totalCredit: 128450.0,
    status: "Posted",
  },
  {
    id: 2,
    refNo: "JNL-2024-0090",
    date: "2024-01-15",
    description: "Supplier payment - PharmaCo Ltd",
    createdBy: "Saman Kumara",
    totalDebit: 45000.0,
    totalCredit: 45000.0,
    status: "Pending Approval",
  },
  {
    id: 3,
    refNo: "JNL-2024-0088",
    date: "2024-01-14",
    description: "Salary expense accrual",
    createdBy: "Saman Kumara",
    totalDebit: 220000.0,
    totalCredit: 220000.0,
    status: "Draft",
  },
];

export const payments = [
  {
    id: 1,
    refNo: "PAY-2024-0034",
    date: "2024-01-15",
    payee: "PharmaCo Ltd",
    type: "Supplier Payment",
    method: "Bank Transfer",
    account: "Commercial Bank - 001",
    amount: 45000.0,
    status: "Posted",
  },
  {
    id: 2,
    refNo: "PAY-2024-0033",
    date: "2024-01-14",
    payee: "MediSupply Co",
    type: "Supplier Payment",
    method: "Cheque",
    account: "HNB - 002",
    amount: 78500.0,
    status: "Posted",
  },
];

// ===================== INVENTORY =====================
export const products = [
  {
    id: 1,
    code: "PRD-001",
    name: "Paracetamol 500mg Tablet",
    genericName: "Paracetamol",
    brand: "Calpol",
    category: "Analgesic",
    manufacturer: "GlaxoSmithKline",
    dosageForm: "Tablet",
    strength: "500mg",
    packSize: "10 tabs/strip",
    unit: "Strip",
    reorderLevel: 100,
    taxCategory: "Standard",
    status: "Active",
  },
  {
    id: 2,
    code: "PRD-002",
    name: "Amoxicillin 250mg Capsule",
    genericName: "Amoxicillin",
    brand: "Wymox",
    category: "Antibiotic",
    manufacturer: "Pfizer",
    dosageForm: "Capsule",
    strength: "250mg",
    packSize: "10 caps",
    unit: "Cap",
    reorderLevel: 50,
    taxCategory: "Standard",
    status: "Active",
  },
  {
    id: 3,
    code: "PRD-003",
    name: "Metformin 500mg Tablet",
    genericName: "Metformin HCl",
    brand: "Glucophage",
    category: "Antidiabetic",
    manufacturer: "Merck",
    dosageForm: "Tablet",
    strength: "500mg",
    packSize: "30 tabs",
    unit: "Tablet",
    reorderLevel: 200,
    taxCategory: "Standard",
    status: "Active",
  },
  {
    id: 4,
    code: "PRD-004",
    name: "Atorvastatin 10mg Tablet",
    genericName: "Atorvastatin",
    brand: "Lipitor",
    category: "Cardiovascular",
    manufacturer: "Pfizer",
    dosageForm: "Tablet",
    strength: "10mg",
    packSize: "30 tabs",
    unit: "Tablet",
    reorderLevel: 150,
    taxCategory: "Standard",
    status: "Active",
  },
  {
    id: 5,
    code: "PRD-005",
    name: "Omeprazole 20mg Capsule",
    genericName: "Omeprazole",
    brand: "Losec",
    category: "GI",
    manufacturer: "AstraZeneca",
    dosageForm: "Capsule",
    strength: "20mg",
    packSize: "14 caps",
    unit: "Cap",
    reorderLevel: 80,
    taxCategory: "Standard",
    status: "Active",
  },
];

export const batches = [
  {
    id: 1,
    product: "Paracetamol 500mg Tablet",
    batchNo: "BATCH-PARACE-0023",
    mfgDate: "2023-06-01",
    expiryDate: "2025-06-01",
    warehouse: "Main Warehouse",
    bin: "A-01",
    availableQty: 2400,
    reservedQty: 200,
    quarantineQty: 0,
    status: "Available",
  },
  {
    id: 2,
    product: "Amoxicillin 250mg Capsule",
    batchNo: "BATCH-AMOX-0045",
    mfgDate: "2023-08-01",
    expiryDate: "2024-02-01",
    warehouse: "Main Warehouse",
    bin: "B-03",
    availableQty: 350,
    reservedQty: 0,
    quarantineQty: 0,
    status: "Near Expiry",
  },
  {
    id: 3,
    product: "Metformin 500mg Tablet",
    batchNo: "BATCH-METF-0012",
    mfgDate: "2023-09-01",
    expiryDate: "2025-09-01",
    warehouse: "Kandy Warehouse",
    bin: "C-02",
    availableQty: 1800,
    reservedQty: 600,
    quarantineQty: 0,
    status: "Available",
  },
];

export const warehouses = [
  {
    id: 1,
    name: "Main Warehouse",
    code: "WH-HO-01",
    branch: "Head Office",
    address: "45 Galle Road, Colombo 03",
    status: "Active",
  },
  {
    id: 2,
    name: "Kandy Warehouse",
    code: "WH-KDY-01",
    branch: "Kandy Branch",
    address: "12 Peradeniya Rd, Kandy",
    status: "Active",
  },
];

export const grns = [
  {
    id: 1,
    refNo: "GRN-2024-0128",
    date: "2024-01-15",
    supplier: "PharmaCo Ltd",
    poRef: "PO-2024-0056",
    receivedBy: "Nimal Silva",
    totalCost: 45000.0,
    status: "Draft",
  },
  {
    id: 2,
    refNo: "GRN-2024-0127",
    date: "2024-01-13",
    supplier: "MediSupply Co",
    poRef: null,
    receivedBy: "Nimal Silva",
    totalCost: 78500.0,
    status: "Posted",
  },
];

// ===================== INVOICE CENTER =====================
export const customers = [
  {
    id: 1,
    code: "CUS-001",
    name: "Colombo Pharmacy",
    email: "cp@cpharmacy.lk",
    phone: "+94 11 567 8901",
    creditLimit: 500000,
    outstanding: 78200,
    status: "Active",
  },
  {
    id: 2,
    code: "CUS-002",
    name: "Kandy Medical Centre",
    email: "kmc@kmc.lk",
    phone: "+94 81 345 6789",
    creditLimit: 300000,
    outstanding: 45000,
    status: "Active",
  },
  {
    id: 3,
    code: "CUS-003",
    name: "Sunrise Drug Store",
    email: "sunrise@drug.lk",
    phone: "+94 77 234 5678",
    creditLimit: 150000,
    outstanding: 0,
    status: "Active",
  },
];

export const invoices = [
  {
    id: 1,
    refNo: "INV-2024-0342",
    date: "2024-01-15",
    customer: "Colombo Pharmacy",
    items: 5,
    subtotal: 38500.0,
    tax: 4620.0,
    discount: 1000.0,
    total: 42120.0,
    paid: 0,
    balance: 42120.0,
    status: "Posted",
  },
  {
    id: 2,
    refNo: "INV-2024-0341",
    date: "2024-01-14",
    customer: "Kandy Medical Centre",
    items: 3,
    subtotal: 22000.0,
    tax: 2640.0,
    discount: 0,
    total: 24640.0,
    paid: 24640.0,
    balance: 0,
    status: "Paid",
  },
  {
    id: 3,
    refNo: "INV-2024-0340",
    date: "2024-01-13",
    customer: "Sunrise Drug Store",
    items: 8,
    subtotal: 56000.0,
    tax: 6720.0,
    discount: 2000.0,
    total: 60720.0,
    paid: 30000.0,
    balance: 30720.0,
    status: "Partially Paid",
  },
];

export const salesOrders = [
  {
    id: 1,
    refNo: "SO-2024-0089",
    date: "2024-01-15",
    customer: "Colombo Pharmacy",
    items: 5,
    total: 42120.0,
    createdBy: "Amal Perera",
    status: "Converted to Invoice",
  },
  {
    id: 2,
    refNo: "SO-2024-0090",
    date: "2024-01-15",
    customer: "Kandy Medical Centre",
    items: 3,
    total: 15000.0,
    createdBy: "Amal Perera",
    status: "Pending Approval",
  },
];

// ===================== COMPLIANCE =====================
export const licenseDocuments = [
  {
    id: 1,
    docType: "Product Registration",
    docNo: "NMRA/2021/PRD/001234",
    related: "Paracetamol 500mg Tablet",
    issueDate: "2021-03-01",
    expiryDate: "2026-03-01",
    status: "Active",
  },
  {
    id: 2,
    docType: "Supplier License",
    docNo: "FDA/2022/SUP/005678",
    related: "PharmaCo Ltd",
    issueDate: "2022-01-15",
    expiryDate: "2024-01-15",
    status: "Expired",
  },
  {
    id: 3,
    docType: "Customer License",
    docNo: "MOH/2023/RET/009012",
    related: "Colombo Pharmacy",
    issueDate: "2023-06-01",
    expiryDate: "2025-06-01",
    status: "Active",
  },
];

export const batchRecalls = [
  {
    id: 1,
    product: "Amoxicillin 250mg Capsule",
    batchNo: "BATCH-AMOX-0020",
    reason: "Manufacturer alert — dissolution issue",
    raisedBy: "Priya Ratne",
    date: "2024-01-10",
    affectedCustomers: 3,
    status: "In Progress",
  },
];

export const suppliers = [
  {
    id: 1,
    code: "SUP-001",
    name: "PharmaCo Ltd",
    email: "sales@pharmaco.lk",
    phone: "+94 11 789 0123",
    creditTerms: "Net 30",
    status: "Active",
  },
  {
    id: 2,
    code: "SUP-002",
    name: "MediSupply Co",
    email: "info@medisupply.lk",
    phone: "+94 11 890 1234",
    creditTerms: "Net 45",
    status: "Active",
  },
];
